# Generated by Django 3.0.2 on 2020-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_id',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
