# Generated by Django 3.0.2 on 2020-01-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='creator_ip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
