# Generated by Django 3.0.2 on 2020-01-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_creator_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='transitions_number',
            field=models.IntegerField(default=0),
        ),
    ]
